### ISSUE TITLE
1.12.2 SASIT Registering but not removing messages from console.

### ISSUE THREAD

**Issue by Osprey4444** [Darkhax-Minecraft/Stuff-A-Sock-In-It#12]
The issue title says it all, here is my config (:

https://hastebin.com/ciyomoxere.coffeescript

**Comment by Darkhax** [comment]
Does it work if you remove the name of the logger? `[minecraft/EntityTrackerEntry]: `

**Comment by kurosnow** [comment]
Having the same issue. No brackets or quotes in my config. You can see SASIT loading at line 850, and then immediately followed by a bunch of stuff that *SHOULD* be filtered out. Was hoping to trim the overly large log of "expected" errors, and make it easier to find errors that need to be fixed, and not clutter space.

    S:BasicFilter <
	Potentially Dangerous alternative prefix
	is missing the required element
	sonar.logistics.core.tiles.displays.info
	reborncore.shields.json.ShieldJsonLoader
	vazkii.patchouli.client.book.BookContents
	crazypants.enderio.base.config.recipes.RecipeFactory
	Could not load tree type from file
	texFix.TextureFix:reloadTextureData
	me.samboycoding.thermaltinkering.ThermalTinkering
	
     >

Latest.log:
https://drive.google.com/open?id=1yPLLpGrgxYKTUfxfDl7lCcX6ZLsuXU1J

**Comment by xJon** [comment]
Indeed it still does not work.

**Comment by Darkhax** [comment]
> 
> 
> Having the same issue. No brackets or quotes in my config. You can see SASIT loading at line 850, and then immediately followed by a bunch of stuff that _SHOULD_ be filtered out. Was hoping to trim the overly large log of "expected" errors, and make it easier to find errors that need to be fixed, and not clutter space.
> 
> ```
> S:BasicFilter <
> Potentially Dangerous alternative prefix
> is missing the required element
> sonar.logistics.core.tiles.displays.info
> reborncore.shields.json.ShieldJsonLoader
> vazkii.patchouli.client.book.BookContents
> crazypants.enderio.base.config.recipes.RecipeFactory
> Could not load tree type from file
> texFix.TextureFix:reloadTextureData
> me.samboycoding.thermaltinkering.ThermalTinkering
> 
>  >
> ```
> 
> Latest.log:
> https://drive.google.com/open?id=1yPLLpGrgxYKTUfxfDl7lCcX6ZLsuXU1J

Your config is working as expected. Things like `sonar.logistics.core.tiles.displays.info` are logger names and should not be used to filter out messages. Your provided log shows that `Potentially Dangerous alternative prefix` and `is missing the required element` which are valid message fragments were not displayed after the mod was loaded.

**Comment by xJon** [comment]
Could it be possible to filter messages according to logger names? E.g. I have this repeated console spam which would be significantly easier to filter out with the logger name. In fact, I can't seem to get rid of it no matter how I setup the config file. Do you have any advice?
```
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: java.lang.NullPointerException
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: 	at toast.lostBooks.book.LostBookCollection.size(LostBookCollection.java:145)
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: 	at toast.lostBooks.book.LostBookCollection.isValidTrade(LostBookCollection.java:131)
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: 	at toast.lostBooks.helper.RandomHelper.chooseTrade(RandomHelper.java:56)
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: 	at toast.lostBooks.book.Library.nextTradeBook(Library.java:98)
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: 	at toast.lostBooks.trade.VillagerBookTrades.func_190888_a(VillagerBookTrades.java:23)
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: 	at jeresources.collection.TradeList.addITradeList(TradeList.java:65)
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: 	at jeresources.entry.VillagerEntry$$Lambda$2023/380235487.accept(Unknown Source)
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: 	at java.util.ArrayList.forEach(ArrayList.java:1249)
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: 	at jeresources.entry.VillagerEntry.addITradeLists(VillagerEntry.java:30)
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: 	at jeresources.entry.VillagerEntry.<init>(VillagerEntry.java:23)
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: 	at jeresources.util.VillagersHelper.initRegistry(VillagersHelper.java:20)
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: 	at jeresources.compatibility.Compatibility.init(Compatibility.java:32)
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: 	at jeresources.proxy.CommonProxy.initCompatibility(CommonProxy.java:14)
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: 	at jeresources.jei.JEIConfig.register(JEIConfig.java:50)
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: 	at mezz.jei.startup.JeiStarter.registerPlugins(JeiStarter.java:213)
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: 	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:77)
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: 	at mezz.jei.startup.ProxyCommonClient.loadComplete(ProxyCommonClient.java:136)
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: 	at mezz.jei.JustEnoughItems.loadComplete(JustEnoughItems.java:55)
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: 	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: 	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:757)
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: 	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3931)
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[03:10:08] [Client thread/INFO]: [toast.lostBooks.book.LostBookCollection:size:148]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by cyberpwnn** [comment]
This mod has never worked.

```

general {
    # A list of strings. If a console message contains any of these, it will be filtered out of the log. [default: ]
    S:BasicFilter <
        Potentially Dangerous alternative prefix
    >
```

```
[21:50:50] [Client thread/WARN] [FML]: Potentially Dangerous alternative prefix `arcanearchives` for name `debugorb`, expected `opensecurity`. This could be a intended override, but in most cases indicates a broken mod.
[21:50:50] [Client thread/WARN] [FML]: Potentially Dangerous alternative prefix `arcanearchives` for name `radiant_key`, expected `opensecurity`. This could be a intended override, but in most cases indicates a broken mod.
[21:50:50] [Client thread/WARN] [FML]: Potentially Dangerous alternative prefix `arcanearchives` for name `gbook_arsenal_condition`, expected `opensecurity`. This could be a intended override, but in most cases indicates a broken mod.
[21:50:50] [Client thread/WARN] [FML]: Potentially Dangerous alternative prefix `arcanearchives` for name `raw_quartz`, expected `opensecurity`. This could be a intended override, but in most cases indicates a broken mod.
[21:50:50] [Client thread/WARN] [FML]: Potentially Dangerous alternative prefix `arcanearchives` for name `shaped_quartz`, expected `opensecurity`. This could be a intended override, but in most cases indicates a broken mod.
[21:50:50] [Client thread/WARN] [FML]: Potentially Dangerous alternative prefix `arcanearchives` for name `manifest`, expected `opensecurity`. This could be a intended override, but in most cases indicates a broken mod.
[21:50:50] [Client thread/WARN] [FML]: Potentially Dangerous alternative prefix `arcanearchives` for name `radiant_amphora`, expected `opensecurity`. This could be a intended override, but in most cases indicates a broken mod.
[21:50:50] [Client thread/WARN] [FML]: Potentially Dangerous alternative prefix `arcanearchives` for name `scepter_revelation`, expected `opensecurity`. This could be a intended override, but in most cases indicates a broken mod.
[21:50:50] [Client thread/WARN] [FML]: Potentially Dangerous alternative prefix `arcanearchives` for name `scepter_manipulation`, expected `opensecurity`. This could be a intended override, but in most cases indicates a broken mod.
[21:50:50] [Client thread/WARN] [FML]: Potentially Dangerous alternative prefix `arcanearchives` for name `tome_arcana`, expected `opensecurity`. This could be a intended override, but in most cases indicates a broken mod.
[21:50:50] [Client thread/WARN] [FML]: Potentially Dangerous alternative prefix `arcanearchives` for name `letter_invitation`, expected `opensecurity`. This could be a intended override, but in most cases indicates a broken mod.
[21:50:50] [Client thread/WARN] [FML]: Potentially Dangerous alternative prefix `arcanearchives` for name `letter_resignation`, expected `opensecurity`. This could be a intended override, but in most cases indicates a broken mod.
[21:50:50] [Client thread/WARN] [FML]: Potentially Dangerous alternative prefix `arcanearchives` for name `writ_expulsion`, expected `opensecurity`. This could be a intended override, but in most cases indicates a broken mod.
[21:50:50] [Client thread/WARN] [FML]: Potentially Dangerous alternative prefix `arcanearchives` for name `containment_field`, expected `opensecurity`. This could be a intended override, but in most cases indicates a broken mod.
[21:50:50] [Client thread/WARN] [FML]: Potentially Dangerous alternative prefix `arcanearchives` for name `matrix_brace`, expected `opensecurity`. This could be a intended override, but in most cases indicates a broken mod.
[21:50:50] [Client thread/WARN] [FML]: Potentially Dangerous alternative prefix `arcanearchives` for name `material_interface`, expected `opensecurity`. This could be a intended override, but in most cases indicates a broken mod.
[21:50:50] [Client thread/WARN] [FML]: Potentially Dangerous alternative prefix `arcanearchives` for name `radiant_dust`, expected `opensecurity`. This could be a intended override, but in most cases indicates a broken mod.
[21:50:50] [Client thread/WARN] [FML]: Potentially Dangerous alternative prefix `arcanearchives` for name `scintillating_inlay`, expected `opensecurity`. This could be a intended override, but in most cases indicates a broken mod.
[21:50:50] [Client thread/WARN] [FML]: Potentially Dangerous alternative prefix `arcanearchives` for name `devouring_charm`, expected `opensecurity`. This could be a intended override, but in most cases indicates a broken mod.
[21:50:50] [Client thread/WARN] [FML]: Potentially Dangerous alternative prefix `arcanearchives` for name `fabrial`, expected `opensecurity`. This could be a intended override, but in most cases indicates a broken mod.
[21:50:50] [Client thread/WARN] [FML]: Potentially Dangerous alternative prefix `arcanearchives` for name `slaughtergleam`, expected `opensecurity`. This could be a intended override, but in most cases indicates a broken mod.
[21:50:50] [Client thread/WARN] [FML]: Potentially Dangerous alternative prefix `arcanearchives` for name `murdergleam`, expected `opensecurity`. This could be a intended override, but in most cases indicates a broken mod.
[21:50:50] [Client thread/WARN] [FML]: Potentially Dangerous alternative prefix `arcanearchives` for name `agegleam`, expected `opensecurity`. This could be a intended override, but in most cases indicates a broken mod.
[21:50:50] [Client thread/WARN] [FML]: Potentially Dangerous alternative prefix `arcanearchives` for name `cleansegleam`, expected `opensecurity`. This could be a intended override, but in most cases indicates a broken mod.
[21:50:50] [Client thread/WARN] [FML]: Potentially Dangerous alternative prefix `arcanearchives` for name `switchgleam`, expected `opensecurity`. This could be a intended override, but in most cases indicates a broken mod.
[21:50:50] [Client thread/WARN] [FML]: Potentially Dangerous alternative prefix `arcanearchives` for name `salvegleam`, expected `opensecurity`. This could be a intended override, but in most cases indicates a broken mod.
[21:50:50] [Client thread/WARN] [FML]: Potentially Dangerous alternative prefix `arcanearchives` for name `munchstone`, expected `opensecurity`. This could be a intended override, but in most cases indicates a broken mod.
[21:50:50] [Client thread/WARN] [FML]: Potentially Dangerous alternative prefix `arcanearchives` for name `transferstone`, expected `opensecurity`. This could be a intended override, but in most cases indicates a broken mod.
[21:50:50] [Client thread/WARN] [FML]: Potentially Dangerous alternative prefix `arcanearchives` for name `orderstone`, expected `opensecurity`. This could be a intended override, but in most cases indicates a broken mod.
[21:50:50] [Client thread/WARN] [FML]: Potentially Dangerous alternative prefix `arcanearchives` for name `mindspindle`, expected `opensecurity`. This could be a intended override, but in most cases indicates a broken mod.
[21:50:50] [Client thread/WARN] [FML]: Potentially Dangerous alternative prefix `arcanearchives` for name `elixirspindle`, expected `opensecurity`. This could be a intended override, but in most cases indicates a broken mod.
[21:50:50] [Client thread/WARN] [FML]: Potentially Dangerous alternative prefix `arcanearchives` for name `mountaintear`, expected `opensecurity`. This could be a intended override, but in most cases indicates a broken mod.
[21:50:50] [Client thread/WARN] [FML]: Potentially Dangerous alternative prefix `arcanearchives` for name `rivertear`, expected `opensecurity`. This could be a intended override, but in most cases indicates a broken mod.
[21:50:50] [Client thread/WARN] [FML]: Potentially Dangerous alternative prefix `arcanearchives` for name `parchtear`, expected `opensecurity`. This could be a intended override, but in most cases indicates a broken mod.
[21:50:50] [Client thread/WARN] [FML]: Potentially Dangerous alternative prefix `arcanearchives` for name `phoenixway`, expected `opensecurity`. This could be a intended override, but in most cases indicates a broken mod.
[21:50:50] [Client thread/WARN] [FML]: Potentially Dangerous alternative prefix `arcanearchives` for name `stormway`, expected `opensecurity`. This could be a intended override, but in most cases indicates a broken mod.
[21:50:50] [Client thread/WARN] [FML]: Potentially Dangerous alternative prefix `arcanearchives` for name `chromatic_powder`, expected `opensecurity`. This could be a intended override, but in most cases indicates a broken mod.
[21:50:50] [Client thread/WARN] [FML]: Potentially Dangerous alternative prefix `arcanearchives` for name `full_spectrum_chromatic_powder`, expected `opensecurity`. This could be a intended override, but in most cases indicates a broken mod.
[21:50:50] [Client thread/WARN] [FML]: Potentially Dangerous alternative prefix `arcanearchives` for name `gemsocket`, expected `opensecurity`. This could be a intended override, but in most cases indicates a broken mod.
```
